### ISSUE TITLE
<inhreited>false</inherited> doesn't work on multi-module project

### ISSUE THREAD

**Issue by sdruskat** [enear/keepachangelog-maven-plugin#6]
Hi, first up, thanks for a useful plugin!

I've run `mvn keepachangelog:release` (v1.2.3) in the parent of a multi-module project (in the root dir which also holds `CHANGELOG.md`).

The goal does update the changelog, but tries to run the goal on modules as well, which leads to a failing build. It seems that `<inherited>false</false>` isn't honoured.

```maven
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for my-tool 0.2.0-SNAPSHOT:
[INFO] 
[INFO] org.my-tool.root .................... SUCCESS [  0.239 s]
[INFO] org.my-tool.bundles ................. FAILURE [  0.359 s]
[INFO] org.my-tool.core .................... SKIPPED
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.056 s
[INFO] Finished at: 2019-11-01T09:28:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'keepachangelog' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/me/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

**Comment by unit73e** [comment]
Hello. I'll see what I can do. It will take a while though, kind of busy lately.

**Comment by unit73e** [comment]
@sdruskat I'm figuring out what's the best option to support running the plugin on the root project only right now and I found out that you can run with the `--non-recursive` option. Like so:

```
mvn keepachangelog:release -N
```

Now this is obviously not the ideal solution because you have to run keepachangelog separately but least it does work.

I also found out that `inherited` is doing something but it's not what I expected. It's simply not giving the configuration to the modules and that's why it fails; because the modules end up not knowing what `keepachange:release` is (since it's not configured) and fail. That being the case I'm not sure if `inherited` is the correct option for this feature. I know other plugins use it so I'll have to check what they're doing. The plugin shouldn't be creating `CHANGELOG.md` files either if they don't exist so I'll fix that as well.

Anyway I knew this would be an headache but it's an important feature to have :)

**Comment by unit73e** [comment]
@sdruskat so after some research I found out that the proper way to execute only on the parent pom is to do something like this:

```xml
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>co.enear.maven.plugins</groupId>
                    <artifactId>keepachangelog-maven-plugin</artifactId>
                    <version>1.3.0</version>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>co.enear.maven.plugins</groupId>
                <artifactId>keepachangelog-maven-plugin</artifactId>
                <version>1.3.0</version>
                <inherited>false</inherited>
                <configuration>
                    <skip>false</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

The modules will know what `keepachangelog` is but skip execution (instead of throwing an error). The parent will have it's own configuration that is not inherited and so only the parent changelog will be changed. For this to work I included the `skip` option. I also fixed some issues while at it. I don't think there's a much better way, at least not with Maven generic options. Maybe I'll add an option to only run on the parent pom to make it easier.

Reality however is that the most common configuration is probably to update the changelog in the `preparation` goal of the `maven-release-plugin`. That way on release the changelog is also updated. I'll add instructions for that when I have spare time.

**Comment by unit73e** [comment]
I've added the `skipModules` option to make this easier. Instructions are included in the readme file.

**Comment by unit73e** [comment]
Closing this issue as it seems to work.
